[profile.metrics]
fail-fast = false
retries = 0
slow-timeout = { period = "10s", terminate-after = 3 }

[profile.metrics.junit]
path = "junit.xml"
store-success-output = false
store-failure-output = true
