//! The `usagi completion <shell>` command: print a shell completion script.
//!
//! Sourcing the printed script enables Tab completion of `usagi` subcommands,
//! flags, and option values in the user's shell (e.g. `usagi <TAB>` lists the
//! commands). The script is generated by [`clap_complete`] from the very same
//! `clap` command tree the binary parses with, so the offered completions stay
//! in lock-step with the actual CLI surface — no hand-maintained word list to
//! drift.
//!
//! The composition root (`src/main.rs`) owns the real `Cli` command tree and the
//! real stdout; this module is the thin, pure seam that writes the generated
//! script into any [`Write`], so it is unit-testable without touching the binary
//! or the terminal.

use std::io::Write;

use clap::Command;
use clap_complete::{generate, Generator};

/// Write `cmd`'s completion script for the shell `generator` into `out`.
///
/// The binary name baked into the script is `cmd`'s own name (`usagi`), so the
/// generated completions drive `usagi …` regardless of where the script is
/// sourced from.
pub fn write<G: Generator, W: Write>(generator: G, cmd: &mut Command, out: &mut W) {
    let name = cmd.get_name().to_string();
    generate(generator, cmd, name, out);
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Command;
    use clap_complete::Shell;

    /// A tiny stand-in command tree (named like the real binary, with one
    /// subcommand) so the test asserts the seam wires the name and tree through
    /// to the generator without depending on the binary's full `Cli`.
    fn fake_cli() -> Command {
        Command::new("usagi").subcommand(Command::new("hop").about("Hop into the welcome screen"))
    }

    #[test]
    fn writes_a_bash_script_naming_the_binary_and_its_subcommand() {
        let mut cmd = fake_cli();
        let mut out: Vec<u8> = Vec::new();

        write(Shell::Bash, &mut cmd, &mut out);

        let script = String::from_utf8(out).expect("completion script is valid UTF-8");
        assert!(script.contains("usagi"), "names the binary: {script}");
        assert!(script.contains("hop"), "offers the subcommand: {script}");
    }

    #[test]
    fn writes_a_zsh_script_for_the_same_tree() {
        let mut cmd = fake_cli();
        let mut out: Vec<u8> = Vec::new();

        write(Shell::Zsh, &mut cmd, &mut out);

        let script = String::from_utf8(out).expect("completion script is valid UTF-8");
        assert!(script.contains("usagi"), "names the binary: {script}");
        assert!(script.contains("hop"), "offers the subcommand: {script}");
    }
}
